project:
  type: website
  output-dir: docs

website:
  title: "BAN400 - R Programming for Data Science"
  image: pictures/nhh.png
  page-navigation: true
  navbar:
    logo: pictures/nhh.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    title: "Menu"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Course overview
      - text: "---"
      - section: "PART 1"
        contents:
        - href: 01-intro-to-r.qmd
          text: "1. Introduction to R"
        - href: 02-data-wrangling.qmd
          text: "2. Data Wrangling"
        - href: 03-graphics.qmd
          text: "3. Graphics"
        - href: 04-functions-and-loops.qmd
          text: "4. Functions and Loops"
        - href: 05-project-organization.qmd
          text: "5. Project organization"
      - section: "PART 2"
        contents:
        - href: 06-git.qmd
          text: "6. Git and Github"
        - href: 07-iterations.qmd
          text: "7. Iterations"
        - href: 08-machine-learning.qmd
          text: "8. Machine learning"
        - href: 09-parallel-computing.qmd
          text: "9. Parallel computing"
        - href: 10-many-models.qmd
          text: "10. many models"
        - href: 11-documentation-and-deployment.qmd
          text: "11. Documentation and deployment"
      - text: "---"
      - section: "Assignments"
        contents:
        - href: assignment-01.qmd
          text: "Assignment 1"
        - href: assignment-02.qmd
          text: "Assignment 2"
        - href: assignment-03.qmd
          text: "Assignment 3"
        - href: assignment-04.qmd
          text: "Assignment 4"

editor: visual


          
format:
  html:
    toc: true
    toc-title: "Contents"
    theme: 
        - cosmo
        - custom.scss
    css: style.css
    fontsize: "1.1em"
    linestretch: "1.7"
    number-sections: true
    shift-heading-level-by: 0
    html-math-method: katex
