# Assignment 2 {.unnumbered}

**Maybe first add some of the straightforward exercises from r4ds?**


For this homework you will practice your data wrangling skills using a survey data set. The data comes from the European Social Survey, and is available at [europeansocialsurvey.org] in various formats. Further, the data from ESS contains many variables with abbreviated/encoded names. The file contains survey responses from Norway in 2016. To get you started with the assignment, you may use the commands below to read in the data set. You may need to install the package `foreign` first in order to use the `read.dta` function. 

```{r, eval=FALSE}
library(foreign)

df <- 
  read.dta("data-ESS8NO.dta") %>%
  transmute(
    party = prtvtbno, 
    age = agea, 
    religiosity = rlgdgr, 
    income_decile = hinctnta)
```

The variables of interest ``prtvtbno``, ``agea``, ``rlgdgr`` and ``hinctnta`` are defined in the attached documentation, together with  more information on the actual questions. To keep it simple, we rename them to `party`, `age`, `religiosity` and `income_decile`. 

1. Provide summary statistics of age of respondents split by the party the respondents voted for last election. Who has the oldest/youngest voters? Where is the standard deviation of voters age the largest? Do not report numbers for parties with less than 25 respondents.

2. The variables religiosity, income_decile and party are encoded as factors. Further, they contain some non-responses such as “Don’t know”, “Refusal” and “No answer”. Find a method for filtering out all the non-responses. How many respondents did not provide an eligible response to each of the questions? How many answered *both* the party and income question? 

3. Filter out all ineligible responses for both income and party. Calculate the *average* religiosity of each party. Provide your answer as a data frame with one row pr. party, sorted by average religiosity. 

4. (**Slightly trickier!**) For each party with more than 75 voters, calculate the ratio of the number of respondents in income deciles 9 and 10 over the number of respondents in income deciles 1 and 2. Which party has the highest high- to low-income voters?


For completeness: When working with survey data, we usually have to apply weights to ensure estimates are representative of the population. This is because a survey sample may be a non-random sample of the general population. The survey data set provides the weights. You don’t have to worry about weights in this assignment, but please store the link “survey data -> weights?!?” in your mind for future work.

